# Contributor: Leonardo Arena <rnalrd@alpinelinux.org>
# Maintainer:
pkgname=py3-django-rest-framework
_pkgname=django-rest-framework
pkgver=3.10.3
pkgrel=1
pkgdesc="Web APIs for Django"
options="!check" # fails with "OperationalError: no such table: auth_user"
url="https://github.com/encode/django-rest-framework"
arch="noarch"
license="Custom"
depends="py3-django"
makedepends="py3-setuptools"
checkdepends="py3-pytest py3-tz py3-core-api py3-jinja2 py3-uritemplate"
source="$pkgname-$pkgver.tar.gz::https://github.com/encode/$_pkgname/archive/$pkgver.tar.gz"
builddir="$srcdir"/$_pkgname-$pkgver

build() {
	python3 setup.py --quiet build
}

check() {
	python3 runtests.py
}

package() {
	python3 setup.py --quiet install --prefix=/usr --root="$pkgdir"
}

sha512sums="7819eaef0acc8ebd5006a99d5126c79508c689c3ab167d72e72d99b584a0f526ab6eac7c23e5baa451d70fd0e381e40f30dabef0002c7bd090aa0c073ab9aca2  py3-django-rest-framework-3.10.3.tar.gz"
